/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Rolando
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jd_admin = new javax.swing.JDialog();
        jb_admin_crearDocente = new javax.swing.JButton();
        jb_admin_crearAlumno = new javax.swing.JButton();
        jb_admin_crearProyecto = new javax.swing.JButton();
        jb_crear_clase = new javax.swing.JButton();
        jb_admin_editar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jb_guardar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jd_docente = new javax.swing.JDialog();
        jd_alumno = new javax.swing.JDialog();
        jd_crear_docente = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        jt_nombre_docente = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jt_apellido_docente = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jt_usuario_docente = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jt_password_docente = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jt_registro_docente = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jt_titulo_docente = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jt_posgrado = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        js_clases = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();
        RB_salud = new javax.swing.JRadioButton();
        RB_licenciatura = new javax.swing.JRadioButton();
        RB_Ingenieria = new javax.swing.JRadioButton();
        jb_agregar_docente = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jd_crear_alumno = new javax.swing.JDialog();
        jLabel15 = new javax.swing.JLabel();
        jt_nombre_alumno = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jt_apellido_alumno = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jt_usuario_alumno = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jt_password_alumno = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jt_registro_alumno = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jt_ID_alumno = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jt_carrera_alumno = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        js_anio_alumno = new javax.swing.JSpinner();
        jLabel23 = new javax.swing.JLabel();
        js_prom_alumno = new javax.swing.JSpinner();
        jLabel24 = new javax.swing.JLabel();
        RB_salud_alumno = new javax.swing.JRadioButton();
        RB_ingenieria_alumno = new javax.swing.JRadioButton();
        RB_licenciatura_alumno = new javax.swing.JRadioButton();
        jb_agregar_alumno = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jd_crear_proyecto = new javax.swing.JDialog();
        jLabel26 = new javax.swing.JLabel();
        jt_titulo_proyecto = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        ScrollPane1 = new javax.swing.JScrollPane();
        jt_descripcion_proyecto = new javax.swing.JTextArea();
        jLabel28 = new javax.swing.JLabel();
        js_punc_proyecto = new javax.swing.JSpinner();
        jLabel29 = new javax.swing.JLabel();
        js_dificultad_proyecto = new javax.swing.JSpinner();
        jLabel30 = new javax.swing.JLabel();
        jt_duracion_proyecto = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        js_participantes_proyecto = new javax.swing.JSpinner();
        jLabel32 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jb_agregar_proyecto = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jd_crear_clase = new javax.swing.JDialog();
        jLabel34 = new javax.swing.JLabel();
        jt_nombre_clase = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jt_seccion_clase = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jt_codigo_clase = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jt_ccarrera_clase = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        js_maxima_clase = new javax.swing.JSpinner();
        jLabel39 = new javax.swing.JLabel();
        jt_numero_clase = new javax.swing.JTextField();
        jb_agregarClase = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        Titulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jt_usuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jp_password = new javax.swing.JPasswordField();
        jb_ingresar = new javax.swing.JButton();
        RB_admin = new javax.swing.JRadioButton();
        RB_docente = new javax.swing.JRadioButton();
        RB_alumno = new javax.swing.JRadioButton();
        Fondo = new javax.swing.JLabel();

        jd_admin.setPreferredSize(new java.awt.Dimension(800, 500));
        jd_admin.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jb_admin_crearDocente.setBackground(new java.awt.Color(255, 255, 0));
        jb_admin_crearDocente.setForeground(new java.awt.Color(0, 0, 0));
        jb_admin_crearDocente.setText("Agregar Docente");
        jb_admin_crearDocente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_admin_crearDocenteMouseClicked(evt);
            }
        });
        jd_admin.getContentPane().add(jb_admin_crearDocente, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        jb_admin_crearAlumno.setBackground(new java.awt.Color(255, 255, 0));
        jb_admin_crearAlumno.setForeground(new java.awt.Color(0, 0, 0));
        jb_admin_crearAlumno.setText("Crear Alumno");
        jb_admin_crearAlumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_admin_crearAlumnoMouseClicked(evt);
            }
        });
        jd_admin.getContentPane().add(jb_admin_crearAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, -1, -1));

        jb_admin_crearProyecto.setBackground(new java.awt.Color(255, 255, 0));
        jb_admin_crearProyecto.setForeground(new java.awt.Color(0, 0, 0));
        jb_admin_crearProyecto.setText("Crear Proyecto");
        jb_admin_crearProyecto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_admin_crearProyectoMouseClicked(evt);
            }
        });
        jd_admin.getContentPane().add(jb_admin_crearProyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, -1, -1));

        jb_crear_clase.setBackground(new java.awt.Color(255, 255, 0));
        jb_crear_clase.setForeground(new java.awt.Color(0, 0, 0));
        jb_crear_clase.setText("Crear Clase");
        jb_crear_clase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_crear_claseMouseClicked(evt);
            }
        });
        jd_admin.getContentPane().add(jb_crear_clase, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 60, -1, -1));

        jb_admin_editar.setBackground(new java.awt.Color(255, 255, 0));
        jb_admin_editar.setForeground(new java.awt.Color(0, 0, 0));
        jb_admin_editar.setText("Editar");
        jb_admin_editar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_admin_editarMouseClicked(evt);
            }
        });
        jd_admin.getContentPane().add(jb_admin_editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 100, 60));

        jTextArea1.setBackground(new java.awt.Color(255, 255, 0));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jd_admin.getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 280, 220));

        jb_guardar.setBackground(new java.awt.Color(255, 255, 0));
        jb_guardar.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jb_guardar.setForeground(new java.awt.Color(0, 0, 0));
        jb_guardar.setText("Guaradar cambios");
        jb_guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_guardarMouseClicked(evt);
            }
        });
        jd_admin.getContentPane().add(jb_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 142, 160, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Principal/color_verde.jpg"))); // NOI18N
        jd_admin.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        javax.swing.GroupLayout jd_docenteLayout = new javax.swing.GroupLayout(jd_docente.getContentPane());
        jd_docente.getContentPane().setLayout(jd_docenteLayout);
        jd_docenteLayout.setHorizontalGroup(
            jd_docenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jd_docenteLayout.setVerticalGroup(
            jd_docenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jd_alumnoLayout = new javax.swing.GroupLayout(jd_alumno.getContentPane());
        jd_alumno.getContentPane().setLayout(jd_alumnoLayout);
        jd_alumnoLayout.setHorizontalGroup(
            jd_alumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jd_alumnoLayout.setVerticalGroup(
            jd_alumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jd_crear_docente.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setText("Nombre:");
        jd_crear_docente.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        jt_nombre_docente.setBackground(new java.awt.Color(255, 255, 0));
        jt_nombre_docente.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jt_nombre_docente.setForeground(new java.awt.Color(0, 0, 0));
        jd_crear_docente.getContentPane().add(jt_nombre_docente, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 180, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 0));
        jLabel6.setText("Apellido:");
        jd_crear_docente.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        jt_apellido_docente.setBackground(new java.awt.Color(255, 255, 0));
        jt_apellido_docente.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jt_apellido_docente.setForeground(new java.awt.Color(0, 0, 0));
        jd_crear_docente.getContentPane().add(jt_apellido_docente, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 180, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 0));
        jLabel7.setText("Usuario:");
        jd_crear_docente.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        jt_usuario_docente.setBackground(new java.awt.Color(255, 255, 0));
        jt_usuario_docente.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jt_usuario_docente.setForeground(new java.awt.Color(0, 0, 0));
        jd_crear_docente.getContentPane().add(jt_usuario_docente, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 180, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 0));
        jLabel8.setText("Contraseña:");
        jd_crear_docente.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        jt_password_docente.setBackground(new java.awt.Color(255, 255, 0));
        jt_password_docente.setForeground(new java.awt.Color(0, 0, 0));
        jd_crear_docente.getContentPane().add(jt_password_docente, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 180, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 0));
        jLabel9.setText("N. de registro:");
        jd_crear_docente.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        jt_registro_docente.setBackground(new java.awt.Color(255, 255, 0));
        jt_registro_docente.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jt_registro_docente.setForeground(new java.awt.Color(0, 0, 0));
        jd_crear_docente.getContentPane().add(jt_registro_docente, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 180, -1));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 0));
        jLabel10.setText("Titulo:");
        jd_crear_docente.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, -1, -1));

        jt_titulo_docente.setBackground(new java.awt.Color(255, 255, 0));
        jt_titulo_docente.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jt_titulo_docente.setForeground(new java.awt.Color(0, 0, 0));
        jd_crear_docente.getContentPane().add(jt_titulo_docente, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 180, -1));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 0));
        jLabel11.setText("Posgrado:");
        jd_crear_docente.getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, -1, -1));

        jt_posgrado.setBackground(new java.awt.Color(255, 255, 0));
        jt_posgrado.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jt_posgrado.setForeground(new java.awt.Color(0, 0, 0));
        jd_crear_docente.getContentPane().add(jt_posgrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 180, -1));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 0));
        jLabel12.setText("Veces que ha impartido clases:");
        jd_crear_docente.getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, -1, 20));

        js_clases.setModel(new javax.swing.SpinnerNumberModel(0, 0, 99, 1));
        jd_crear_docente.getContentPane().add(js_clases, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 50, -1, -1));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 0));
        jLabel13.setText("Facultad:");
        jd_crear_docente.getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, -1, -1));

        buttonGroup2.add(RB_salud);
        RB_salud.setForeground(new java.awt.Color(255, 255, 0));
        RB_salud.setSelected(true);
        RB_salud.setText("Salud");
        jd_crear_docente.getContentPane().add(RB_salud, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, -1, -1));

        buttonGroup2.add(RB_licenciatura);
        RB_licenciatura.setForeground(new java.awt.Color(255, 255, 0));
        RB_licenciatura.setText("Licenciatura");
        jd_crear_docente.getContentPane().add(RB_licenciatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 100, -1, -1));

        buttonGroup2.add(RB_Ingenieria);
        RB_Ingenieria.setForeground(new java.awt.Color(255, 255, 0));
        RB_Ingenieria.setText("Ingenieria");
        jd_crear_docente.getContentPane().add(RB_Ingenieria, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 100, -1, -1));

        jb_agregar_docente.setBackground(new java.awt.Color(255, 255, 0));
        jb_agregar_docente.setForeground(new java.awt.Color(0, 0, 0));
        jb_agregar_docente.setText("Agregar");
        jb_agregar_docente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_agregar_docenteMouseClicked(evt);
            }
        });
        jd_crear_docente.getContentPane().add(jb_agregar_docente, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Principal/rojo.jpg"))); // NOI18N
        jd_crear_docente.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        jd_crear_alumno.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 0));
        jLabel15.setText("Nombre:");
        jd_crear_alumno.getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        jt_nombre_alumno.setBackground(new java.awt.Color(255, 255, 0));
        jt_nombre_alumno.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jt_nombre_alumno.setForeground(new java.awt.Color(0, 0, 0));
        jd_crear_alumno.getContentPane().add(jt_nombre_alumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 190, -1));

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 0));
        jLabel16.setText("Apellido:");
        jd_crear_alumno.getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        jt_apellido_alumno.setBackground(new java.awt.Color(255, 255, 0));
        jt_apellido_alumno.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jt_apellido_alumno.setForeground(new java.awt.Color(0, 0, 0));
        jd_crear_alumno.getContentPane().add(jt_apellido_alumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 190, -1));

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 0));
        jLabel17.setText("Usuario:");
        jd_crear_alumno.getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        jt_usuario_alumno.setBackground(new java.awt.Color(255, 255, 0));
        jt_usuario_alumno.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jt_usuario_alumno.setForeground(new java.awt.Color(0, 0, 0));
        jd_crear_alumno.getContentPane().add(jt_usuario_alumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 190, -1));

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 0));
        jLabel18.setText("Password:");
        jd_crear_alumno.getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        jt_password_alumno.setBackground(new java.awt.Color(255, 255, 0));
        jt_password_alumno.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jt_password_alumno.setForeground(new java.awt.Color(0, 0, 0));
        jd_crear_alumno.getContentPane().add(jt_password_alumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 190, -1));

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 0));
        jLabel19.setText("N. de registro:");
        jd_crear_alumno.getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        jt_registro_alumno.setBackground(new java.awt.Color(255, 255, 0));
        jt_registro_alumno.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jt_registro_alumno.setForeground(new java.awt.Color(0, 0, 0));
        jd_crear_alumno.getContentPane().add(jt_registro_alumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 190, -1));

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 0));
        jLabel20.setText("ID:");
        jd_crear_alumno.getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, -1, -1));

        jt_ID_alumno.setBackground(new java.awt.Color(255, 255, 0));
        jt_ID_alumno.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jt_ID_alumno.setForeground(new java.awt.Color(0, 0, 0));
        jd_crear_alumno.getContentPane().add(jt_ID_alumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 190, -1));

        jLabel21.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 0));
        jLabel21.setText("Carrera:");
        jd_crear_alumno.getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, -1, -1));

        jt_carrera_alumno.setBackground(new java.awt.Color(255, 255, 0));
        jt_carrera_alumno.setForeground(new java.awt.Color(0, 0, 0));
        jd_crear_alumno.getContentPane().add(jt_carrera_alumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, 190, -1));

        jLabel22.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 0));
        jLabel22.setText("Año de la carrera:");
        jd_crear_alumno.getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, -1, -1));

        js_anio_alumno.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));
        jd_crear_alumno.getContentPane().add(js_anio_alumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 50, -1, -1));

        jLabel23.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 0));
        jLabel23.setText("Promedio:");
        jd_crear_alumno.getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, -1, -1));

        js_prom_alumno.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 0.0d, 0.1d));
        jd_crear_alumno.getContentPane().add(js_prom_alumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 110, -1, -1));

        jLabel24.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 0));
        jLabel24.setText("Facultad:");
        jd_crear_alumno.getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, -1, -1));

        buttonGroup3.add(RB_salud_alumno);
        RB_salud_alumno.setForeground(new java.awt.Color(255, 255, 0));
        RB_salud_alumno.setSelected(true);
        RB_salud_alumno.setText("Salud");
        jd_crear_alumno.getContentPane().add(RB_salud_alumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 170, -1, -1));

        RB_ingenieria_alumno.setForeground(new java.awt.Color(255, 255, 0));
        RB_ingenieria_alumno.setText("Ingenieria");
        jd_crear_alumno.getContentPane().add(RB_ingenieria_alumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 170, -1, -1));

        RB_licenciatura_alumno.setForeground(new java.awt.Color(255, 255, 0));
        RB_licenciatura_alumno.setText("Licenciatura");
        jd_crear_alumno.getContentPane().add(RB_licenciatura_alumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 170, -1, -1));

        jb_agregar_alumno.setBackground(new java.awt.Color(255, 255, 0));
        jb_agregar_alumno.setForeground(new java.awt.Color(0, 0, 0));
        jb_agregar_alumno.setText("Agregar");
        jb_agregar_alumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_agregar_alumnoMouseClicked(evt);
            }
        });
        jd_crear_alumno.getContentPane().add(jb_agregar_alumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Principal/rojo.jpg"))); // NOI18N
        jd_crear_alumno.getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        jd_crear_proyecto.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 0));
        jLabel26.setText("Titulo:");
        jd_crear_proyecto.getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jt_titulo_proyecto.setBackground(new java.awt.Color(255, 255, 0));
        jt_titulo_proyecto.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jt_titulo_proyecto.setForeground(new java.awt.Color(0, 0, 0));
        jd_crear_proyecto.getContentPane().add(jt_titulo_proyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 210, -1));

        jLabel27.setForeground(new java.awt.Color(255, 255, 0));
        jLabel27.setText("Descripcion:");
        jd_crear_proyecto.getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        jt_descripcion_proyecto.setBackground(new java.awt.Color(255, 255, 0));
        jt_descripcion_proyecto.setColumns(20);
        jt_descripcion_proyecto.setForeground(new java.awt.Color(0, 0, 0));
        jt_descripcion_proyecto.setRows(5);
        ScrollPane1.setViewportView(jt_descripcion_proyecto);

        jd_crear_proyecto.getContentPane().add(ScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 230, 110));

        jLabel28.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 0));
        jLabel28.setText("Puntuacion:");
        jd_crear_proyecto.getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        js_punc_proyecto.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));
        jd_crear_proyecto.getContentPane().add(js_punc_proyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, -1));

        jLabel29.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 0));
        jLabel29.setText("Dificultad:");
        jd_crear_proyecto.getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        js_dificultad_proyecto.setModel(new javax.swing.SpinnerNumberModel(1, 0, 5, 1));
        jd_crear_proyecto.getContentPane().add(js_dificultad_proyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, -1));

        jLabel30.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 0));
        jLabel30.setText("Duracion:");
        jd_crear_proyecto.getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jt_duracion_proyecto.setBackground(new java.awt.Color(255, 255, 0));
        jt_duracion_proyecto.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jt_duracion_proyecto.setForeground(new java.awt.Color(0, 0, 0));
        jd_crear_proyecto.getContentPane().add(jt_duracion_proyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 190, -1));

        jLabel31.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 0));
        jLabel31.setText("Participantes:");
        jd_crear_proyecto.getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        js_participantes_proyecto.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
        jd_crear_proyecto.getContentPane().add(js_participantes_proyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, -1, -1));

        jLabel32.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 0));
        jLabel32.setText("Fecha de entrega:");
        jd_crear_proyecto.getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, -1, -1));
        jd_crear_proyecto.getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, -1, -1));

        jb_agregar_proyecto.setBackground(new java.awt.Color(255, 255, 0));
        jb_agregar_proyecto.setForeground(new java.awt.Color(0, 0, 0));
        jb_agregar_proyecto.setText("Agregar");
        jb_agregar_proyecto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_agregar_proyectoMouseClicked(evt);
            }
        });
        jd_crear_proyecto.getContentPane().add(jb_agregar_proyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, -1, -1));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Principal/rojo.jpg"))); // NOI18N
        jd_crear_proyecto.getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        jd_crear_clase.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel34.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 0));
        jLabel34.setText("Nombre:");
        jd_crear_clase.getContentPane().add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        jt_nombre_clase.setBackground(new java.awt.Color(255, 255, 0));
        jt_nombre_clase.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jt_nombre_clase.setForeground(new java.awt.Color(0, 0, 0));
        jd_crear_clase.getContentPane().add(jt_nombre_clase, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 210, -1));

        jLabel35.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 0));
        jLabel35.setText("Seccion:");
        jd_crear_clase.getContentPane().add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        jt_seccion_clase.setBackground(new java.awt.Color(255, 255, 0));
        jt_seccion_clase.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jt_seccion_clase.setForeground(new java.awt.Color(0, 0, 0));
        jd_crear_clase.getContentPane().add(jt_seccion_clase, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 210, -1));

        jLabel36.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 0));
        jLabel36.setText("Codigo:");
        jd_crear_clase.getContentPane().add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        jt_codigo_clase.setBackground(new java.awt.Color(255, 255, 0));
        jt_codigo_clase.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jt_codigo_clase.setForeground(new java.awt.Color(0, 0, 0));
        jd_crear_clase.getContentPane().add(jt_codigo_clase, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 210, -1));

        jLabel37.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 0));
        jLabel37.setText("codigo carrera.");
        jd_crear_clase.getContentPane().add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jt_ccarrera_clase.setBackground(new java.awt.Color(255, 255, 0));
        jt_ccarrera_clase.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jt_ccarrera_clase.setForeground(new java.awt.Color(0, 0, 0));
        jd_crear_clase.getContentPane().add(jt_ccarrera_clase, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 200, -1));

        jLabel38.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 0));
        jLabel38.setText("Capacidad Maxima:");
        jd_crear_clase.getContentPane().add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        js_maxima_clase.setModel(new javax.swing.SpinnerNumberModel(1, 1, 30, 1));
        jd_crear_clase.getContentPane().add(js_maxima_clase, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, -1, -1));

        jLabel39.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 0));
        jLabel39.setText("Numero de la clase:");
        jd_crear_clase.getContentPane().add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, -1));

        jt_numero_clase.setBackground(new java.awt.Color(255, 255, 0));
        jt_numero_clase.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jt_numero_clase.setForeground(new java.awt.Color(0, 0, 0));
        jd_crear_clase.getContentPane().add(jt_numero_clase, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, 220, -1));

        jb_agregarClase.setText("Agregar");
        jb_agregarClase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_agregarClaseMouseClicked(evt);
            }
        });
        jd_crear_clase.getContentPane().add(jb_agregarClase, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, -1, -1));

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Principal/rojo.jpg"))); // NOI18N
        jd_crear_clase.getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setPreferredSize(new java.awt.Dimension(800, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        Titulo.setForeground(new java.awt.Color(0, 0, 153));
        Titulo.setText("Ingresar al Sistema");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, -1, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Usuario:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, -1, -1));

        jt_usuario.setBackground(new java.awt.Color(0, 0, 153));
        jt_usuario.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jt_usuario.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jt_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 220, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setText("Contraseña:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));

        jp_password.setBackground(new java.awt.Color(0, 0, 153));
        jp_password.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jp_password.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jp_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 220, -1));

        jb_ingresar.setBackground(new java.awt.Color(0, 0, 153));
        jb_ingresar.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jb_ingresar.setForeground(new java.awt.Color(255, 255, 255));
        jb_ingresar.setText("Ingresar");
        jb_ingresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_ingresarMouseClicked(evt);
            }
        });
        getContentPane().add(jb_ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, -1, -1));

        buttonGroup1.add(RB_admin);
        RB_admin.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        RB_admin.setForeground(new java.awt.Color(0, 0, 153));
        RB_admin.setSelected(true);
        RB_admin.setText("Administrador");
        getContentPane().add(RB_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, -1, -1));

        buttonGroup1.add(RB_docente);
        RB_docente.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        RB_docente.setForeground(new java.awt.Color(0, 0, 153));
        RB_docente.setText("Docente");
        getContentPane().add(RB_docente, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 380, -1, -1));

        buttonGroup1.add(RB_alumno);
        RB_alumno.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        RB_alumno.setForeground(new java.awt.Color(0, 0, 153));
        RB_alumno.setText("alumno");
        getContentPane().add(RB_alumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 380, -1, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Principal/fondo_celeste.jpg"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_ingresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_ingresarMouseClicked
        // TODO add your handling code here:
        if (RB_admin.isSelected()){
            String a = jt_usuario.getText();
            String b = jp_password.getText();
            if (a.equals("admin")&&b.equals("1234")){
                abrirAdmin();
            }
            else
            {
                JOptionPane.showMessageDialog(this, "usuario/contraseña incorrecta");
            }
        }
        if (RB_docente.isSelected()){
            String a = jt_usuario.getText();
            String b = jp_password.getText();
            boolean centinela = false;
            for (int i = 0; i < docentes.size(); i++) {
                String u = docentes.get(i).getUsuario();
                String p = docentes.get(i).getPassword();
                if (u.equals(a)&&p.equals(b)){
                    centinela = true;
                }
            }
            if (centinela==true){
                abrirDocente();
            }
            else{
                JOptionPane.showMessageDialog(this, "usuario/contraseña incorrectos");
            }
        }
        if (RB_alumno.isSelected()){
            String a = jt_usuario.getText();
            String b = jp_password.getText();
            boolean centinela = false;
            for (int i = 0; i < docentes.size(); i++) {
                String u = docentes.get(i).getUsuario();
                String p = docentes.get(i).getPassword();
                if (u.equals(a)&&p.equals(b)){
                    centinela = true;
                }
            }
            if (centinela==true){
                abrirAlumno();
            }
            else{
                JOptionPane.showMessageDialog(this, "usuario/contraseña incorrectos");
            }
        }
    }//GEN-LAST:event_jb_ingresarMouseClicked

    private void jb_agregar_docenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_agregar_docenteMouseClicked
        // TODO add your handling code here:
        crearDocente();
    }//GEN-LAST:event_jb_agregar_docenteMouseClicked

    private void jb_admin_crearDocenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_admin_crearDocenteMouseClicked
        // TODO add your handling code here:
        jd_crear_docente.setModal(true);
        jd_crear_docente.pack();
        jd_crear_docente.setLocationRelativeTo(jd_admin);
        jd_crear_docente.setVisible(true);
    }//GEN-LAST:event_jb_admin_crearDocenteMouseClicked

    private void jb_agregar_alumnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_agregar_alumnoMouseClicked
        // TODO add your handling code here:
        crearAlumno();
    }//GEN-LAST:event_jb_agregar_alumnoMouseClicked

    private void jb_admin_crearAlumnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_admin_crearAlumnoMouseClicked
        // TODO add your handling code here:
        jd_crear_alumno.setModal(true);
        jd_crear_alumno.pack();
        jd_crear_alumno.setLocationRelativeTo(jd_admin);
        jd_crear_alumno.setVisible(true);
    }//GEN-LAST:event_jb_admin_crearAlumnoMouseClicked

    private void jb_admin_crearProyectoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_admin_crearProyectoMouseClicked
        // TODO add your handling code here:
        jd_crear_proyecto.setModal(true);
        jd_crear_proyecto.pack();
        jd_crear_proyecto.setLocationRelativeTo(jd_admin);
        jd_crear_proyecto.setVisible(true);
    }//GEN-LAST:event_jb_admin_crearProyectoMouseClicked

    private void jb_agregar_proyectoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_agregar_proyectoMouseClicked
        // TODO add your handling code here:
        crearProyecto();
    }//GEN-LAST:event_jb_agregar_proyectoMouseClicked

    private void jb_crear_claseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_crear_claseMouseClicked
        // TODO add your handling code here:
        jd_crear_clase.setModal(true);
        jd_crear_clase.pack();
        jd_crear_clase.setLocationRelativeTo(jd_admin);
        jd_crear_clase.setVisible(true);
    }//GEN-LAST:event_jb_crear_claseMouseClicked

    private void jb_agregarClaseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_agregarClaseMouseClicked
        // TODO add your handling code here:
        crearClase();
    }//GEN-LAST:event_jb_agregarClaseMouseClicked

    private void jb_admin_editarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_admin_editarMouseClicked
        // TODO add your handling code here:
        JFileChooser jfc = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos de texto","txt");
        jfc.addChoosableFileFilter(filtro);
        jfc.showOpenDialog(jd_admin);
        File archivo = null;
        FileReader canal = null;
        BufferedReader ram = null;
        String m="";
        try {
            archivo = new File(jfc.getSelectedFile().getPath());
            canal = new FileReader(archivo);
            ram = new BufferedReader(canal);
            String linea;
            while ((linea=ram.readLine())!=null){
                m += linea;
            }
            jTextArea1.setText(m);
        }
        catch (Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jb_admin_editarMouseClicked

    private void jb_guardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_guardarMouseClicked
        // TODO add your handling code here:
        JFileChooser jfc = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos de texto","txt");
        jfc.addChoosableFileFilter(filtro);
        int seleccion = jfc.showSaveDialog(jd_crear_docente);
        FileWriter fw = null;
        BufferedWriter bw = null;
        if (seleccion==JFileChooser.APPROVE_OPTION){
            try{
                File fichero = null;
                if (jfc.getFileFilter().getDescription().equals("Archivos de texto")){
                    fichero = new File(jfc.getSelectedFile().getPath()+".txt");
                }
                else{
                    fichero = jfc.getSelectedFile();
                }
                fw = new FileWriter(fichero);
                bw = new BufferedWriter(fw);
                bw.write(jTextArea1.getText());
                bw.flush();
            }
            catch (Exception e){
                e.printStackTrace();
            }
            try{
                bw.close();
                fw.close();
            }
            catch (IOException ex){
                
            }
        }
    }//GEN-LAST:event_jb_guardarMouseClicked

    public void abrirAdmin(){
        jd_admin.setModal(true);
        jd_admin.pack();
        jd_admin.setLocationRelativeTo(this);
        jd_admin.setVisible(true);
    }
    
    public void abrirDocente(){
        jd_docente.setModal(true);
        jd_docente.pack();
        jd_docente.setLocationRelativeTo(this);
        jd_docente.setVisible(true);
    }
    
    public void abrirAlumno(){
        jd_alumno.setModal(true);
        jd_alumno.pack();
        jd_alumno.setLocationRelativeTo(this);
        jd_alumno.setVisible(true);
    }
    
    public void crearDocente(){
        docente D = new docente();
        D.setNombre(jt_nombre_docente.getText());
        D.setApellido(jt_apellido_docente.getText());
        D.setUsuario(jt_usuario_docente.getText());
        D.setPassword(jt_password_docente.getText());
        D.setN_registro(jt_registro_docente.getText());
        D.setTitulo(jt_titulo_docente.getText());
        D.setImpartido_clase((Integer)js_clases.getValue());
        if (RB_salud.isSelected()){
            D.setFacultad("salud");
        }
        if (RB_licenciatura.isSelected()){
            D.setFacultad("licenciatura");
        }
        if (RB_Ingenieria.isSelected()){
            D.setFacultad("ingenieria");
        }
        docentes.add(D);
        JFileChooser jfc = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos de texto","txt");
        jfc.addChoosableFileFilter(filtro);
        int seleccion = jfc.showSaveDialog(jd_crear_docente);
        FileWriter fw = null;
        BufferedWriter bw = null;
        if (seleccion==JFileChooser.APPROVE_OPTION){
            try{
                File fichero = null;
                if (jfc.getFileFilter().getDescription().equals("Archivos de texto")){
                    fichero = new File(jfc.getSelectedFile().getPath()+".txt");
                }
                else{
                    fichero = jfc.getSelectedFile();
                }
                fw = new FileWriter(fichero);
                bw = new BufferedWriter(fw);
                bw.write(D.toString());
                bw.flush();
            }
            catch (Exception e){
                e.printStackTrace();
            }
            try{
                bw.close();
                fw.close();
            }
            catch (IOException ex){
                
            }
        }
        jt_nombre_docente.setText("");
        jt_apellido_docente.setText("");
        jt_usuario_docente.setText("");
        jt_password_docente.setText("");
        jt_registro_docente.setText("");
        jt_titulo_docente.setText("");
    }
    
    public void crearAlumno(){
        alumno A = new alumno();
        A.setNombre(jt_nombre_alumno.getText());
        A.setApellido(jt_apellido_alumno.getText());
        A.setUsuario(jt_usuario_alumno.getText());
        A.setPassword(jt_password_alumno.getText());
        A.setRegistro(jt_registro_alumno.getText());
        A.setID(jt_ID_alumno.getText());
        A.setCarrera(jt_carrera_alumno.getText());
        A.setAnio((Integer)js_anio_alumno.getValue());
        A.setPromedio((Double)js_prom_alumno.getValue());
        if (RB_salud.isSelected()){
            A.setFacultad("salud");
        }
        if (RB_ingenieria_alumno.isSelected()){
            A.setFacultad("ingenieria");
        }
        if (RB_licenciatura_alumno.isSelected()){
            A.setFacultad("licenciatura");
        }
        alumnos.add(A);
        JFileChooser jfc = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos de texto","txt");
        jfc.addChoosableFileFilter(filtro);
        int seleccion = jfc.showSaveDialog(jd_crear_docente);
        FileWriter fw = null;
        BufferedWriter bw = null;
        if (seleccion==JFileChooser.APPROVE_OPTION){
            try{
                File fichero = null;
                if (jfc.getFileFilter().getDescription().equals("Archivos de texto")){
                    fichero = new File(jfc.getSelectedFile().getPath()+".txt");
                }
                else{
                    fichero = jfc.getSelectedFile();
                }
                fw = new FileWriter(fichero);
                bw = new BufferedWriter(fw);
                bw.write(A.toString());
                bw.flush();
            }
            catch (Exception e){
                e.printStackTrace();
            }
            try{
                bw.close();
                fw.close();
            }
            catch (IOException ex){
                
            }
        }
        jt_nombre_alumno.setText("");
        jt_apellido_alumno.setText("");
        jt_usuario_alumno.setText("");
        jt_password_alumno.setText("");
        jt_registro_alumno.setText("");
        jt_ID_alumno.setText("");
        jt_carrera_alumno.setText("");
    }
    
    public void crearProyecto(){
        proyecto P = new proyecto();
        P.setTitulo(jt_titulo_proyecto.getText());
        P.setDescripcion(jt_descripcion_proyecto.getText());
        P.setPuntuacion((Integer)js_punc_proyecto.getValue());
        P.setDificultad((Integer)js_dificultad_proyecto.getValue());
        P.setDuracion(jt_duracion_proyecto.getText());
        P.setParticipantes((Integer)js_participantes_proyecto.getValue());
        P.setEntrega(jDateChooser1.getDate());
        JFileChooser jfc = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos de texto","txt");
        jfc.addChoosableFileFilter(filtro);
        int seleccion = jfc.showSaveDialog(jd_crear_docente);
        FileWriter fw = null;
        BufferedWriter bw = null;
        if (seleccion==JFileChooser.APPROVE_OPTION){
            try{
                File fichero = null;
                if (jfc.getFileFilter().getDescription().equals("Archivos de texto")){
                    fichero = new File(jfc.getSelectedFile().getPath()+".txt");
                }
                else{
                    fichero = jfc.getSelectedFile();
                }
                fw = new FileWriter(fichero);
                bw = new BufferedWriter(fw);
                bw.write(P.toString());
                bw.flush();
            }
            catch (Exception e){
                e.printStackTrace();
            }
            try{
                bw.close();
                fw.close();
            }
            catch (IOException ex){
                
            }
        }
        jt_titulo_proyecto.setText("");
        jt_descripcion_proyecto.setText("");
        jt_duracion_proyecto.setText("");
    }
    
    public void crearClase(){
        clase C = new clase();
        C.setNombre(jt_nombre_clase.getText());
        C.setSeccion(jt_seccion_clase.getText());
        C.setCodigo(jt_codigo_clase.getText());
        C.setC_carrera(jt_ccarrera_clase.getText());
        C.setMaxima((Integer)js_maxima_clase.getValue());
        C.setNumero(Integer.parseInt(jt_numero_clase.getText()));
        JFileChooser jfc = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos de texto","txt");
        jfc.addChoosableFileFilter(filtro);
        int seleccion = jfc.showSaveDialog(jd_crear_docente);
        FileWriter fw = null;
        BufferedWriter bw = null;
        if (seleccion==JFileChooser.APPROVE_OPTION){
            try{
                File fichero = null;
                if (jfc.getFileFilter().getDescription().equals("Archivos de texto")){
                    fichero = new File(jfc.getSelectedFile().getPath()+".txt");
                }
                else{
                    fichero = jfc.getSelectedFile();
                }
                fw = new FileWriter(fichero);
                bw = new BufferedWriter(fw);
                bw.write(C.toString());
                bw.flush();
            }
            catch (Exception e){
                e.printStackTrace();
            }
            try{
                bw.close();
                fw.close();
            }
            catch (IOException ex){
                
            }
        }
        jt_nombre_clase.setText("");
        jt_seccion_clase.setText("");
        jt_codigo_clase.setText("");
        jt_ccarrera_clase.setText("");
        jt_numero_clase.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    ArrayList<docente> docentes = new ArrayList();
    ArrayList<alumno> alumnos = new ArrayList();
    proyecto proyecto_creado;
    int posicion;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JRadioButton RB_Ingenieria;
    private javax.swing.JRadioButton RB_admin;
    private javax.swing.JRadioButton RB_alumno;
    private javax.swing.JRadioButton RB_docente;
    private javax.swing.JRadioButton RB_ingenieria_alumno;
    private javax.swing.JRadioButton RB_licenciatura;
    private javax.swing.JRadioButton RB_licenciatura_alumno;
    private javax.swing.JRadioButton RB_salud;
    private javax.swing.JRadioButton RB_salud_alumno;
    private javax.swing.JScrollPane ScrollPane1;
    private javax.swing.JLabel Titulo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton jb_admin_crearAlumno;
    private javax.swing.JButton jb_admin_crearDocente;
    private javax.swing.JButton jb_admin_crearProyecto;
    private javax.swing.JButton jb_admin_editar;
    private javax.swing.JButton jb_agregarClase;
    private javax.swing.JButton jb_agregar_alumno;
    private javax.swing.JButton jb_agregar_docente;
    private javax.swing.JButton jb_agregar_proyecto;
    private javax.swing.JButton jb_crear_clase;
    private javax.swing.JButton jb_guardar;
    private javax.swing.JButton jb_ingresar;
    private javax.swing.JDialog jd_admin;
    private javax.swing.JDialog jd_alumno;
    private javax.swing.JDialog jd_crear_alumno;
    private javax.swing.JDialog jd_crear_clase;
    private javax.swing.JDialog jd_crear_docente;
    private javax.swing.JDialog jd_crear_proyecto;
    private javax.swing.JDialog jd_docente;
    private javax.swing.JPasswordField jp_password;
    private javax.swing.JSpinner js_anio_alumno;
    private javax.swing.JSpinner js_clases;
    private javax.swing.JSpinner js_dificultad_proyecto;
    private javax.swing.JSpinner js_maxima_clase;
    private javax.swing.JSpinner js_participantes_proyecto;
    private javax.swing.JSpinner js_prom_alumno;
    private javax.swing.JSpinner js_punc_proyecto;
    private javax.swing.JTextField jt_ID_alumno;
    private javax.swing.JTextField jt_apellido_alumno;
    private javax.swing.JTextField jt_apellido_docente;
    private javax.swing.JTextField jt_carrera_alumno;
    private javax.swing.JTextField jt_ccarrera_clase;
    private javax.swing.JTextField jt_codigo_clase;
    private javax.swing.JTextArea jt_descripcion_proyecto;
    private javax.swing.JTextField jt_duracion_proyecto;
    private javax.swing.JTextField jt_nombre_alumno;
    private javax.swing.JTextField jt_nombre_clase;
    private javax.swing.JTextField jt_nombre_docente;
    private javax.swing.JTextField jt_numero_clase;
    private javax.swing.JTextField jt_password_alumno;
    private javax.swing.JTextField jt_password_docente;
    private javax.swing.JTextField jt_posgrado;
    private javax.swing.JTextField jt_registro_alumno;
    private javax.swing.JTextField jt_registro_docente;
    private javax.swing.JTextField jt_seccion_clase;
    private javax.swing.JTextField jt_titulo_docente;
    private javax.swing.JTextField jt_titulo_proyecto;
    private javax.swing.JTextField jt_usuario;
    private javax.swing.JTextField jt_usuario_alumno;
    private javax.swing.JTextField jt_usuario_docente;
    // End of variables declaration//GEN-END:variables
}
